apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nest-argo-app
spec:
  project: default
  source:
    repoURL: 'https://github.com/diemtrang-bic/nest-sample.git'
    path: manifests
  destination:
    server: 'https://192.168.49.2:8443'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
