apiVersion: batch/v1
kind: Job
metadata:
  name: test
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: test
          image: tranghapham/test:main
          imagePullPolicy: Always
      restartPolicy: Never
