apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-app
  template:
    metadata:
      labels:
        app: nest-app
    spec:
      containers:
        - name: nest-app
          image: nest-image:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
